wrapper

diff --git a/icc-wrapper b/icc-wrapper
--- a/icc-wrapper
+++ b/icc-wrapper
@@ -1,2 +1,21 @@
 #!/usr/bin/sh
-icc -fno-strict-aliasing $*
+
+ARGS=$@
+ICCARGS=""
+
+for ARG in $ARGS
+do
+    case $ARG in -mno-mmx | -mno-3dnow | -falign-jumps=1 | -funit-at-a-time | -Wno-frame-address | -Wno-format-truncation | -Wno-format-overflow | -Wno-int-in-bool-context | -Wframe-larger-than=2048 | -Wno-unused-const-variable | -fno-stack-check | -fconserve-stack)
+        ;;
+    * )
+        ICCARGS="$ICCARGS $ARG"
+        ;;
+    esac
+done
+
+icc -fno-strict-aliasing $ICCARGS
+ret=$?
+
+[ $ret -ne 0 ] && echo ">>>>>icc-wrapper $ARGS<<<<<>>>>>icc $ICCARGS<<<<< failed with status $ret. Launching gcc..." && gcc $ICCARGS
+
+exit $?
