wrapper-update

diff --git a/icc-wrapper b/icc-wrapper
--- a/icc-wrapper
+++ b/icc-wrapper
@@ -5,14 +5,23 @@ ICCARGS=""
 for ARG in ${ARGS};
 do
     case $ARG in
--mno-mmx | -mno-3dnow | -falign-jumps=1 | -funit-at-a-time | -Wno-frame-address | -Wno-format-truncation | -Wno-format-overflow | -Wno-int-in-bool-context | -Wframe-larger-than=2048 | -Wno-unused-const-variable | -fno-stack-check | -fconserve-stack)
-        ;;
-    * )
-        ICCARGS="$ICCARGS $ARG"
-        ;;
+        -mno-mmx | -mno-3dnow | -falign-jumps=1 | -funit-at-a-time | -Wno-frame-address | -Wno-format-truncation | -Wno-format-overflow | -Wno-int-in-bool-context | -Wframe-larger-than=2048 | -Wno-unused-const-variable | -fno-stack-check | -fconserve-stack )
+            ;;
+        -falign-jumps=1 )
+            ICCARGS="${ICCARGS} -fno-align-loops"
+            ;;
+        -fno-stack-check )
+            ICCARGS="${ICCARGS} -fno-stack-security-check"
+            ;;
+        * )
+            ICCARGS="${ICCARGS} $ARG"
+            ;;
     esac
 done
 
-icc -fno-strict-aliasing ${ICCARGS} && exit 0
-echo ">>>>>icc-wrapper ${ARGS} <<<<<>>>>>icc ${ICCARGS} <<<<< failed with status $ret. Launching gcc..."  >> /tmp/fuck-icc.log && gcc ${ICCARGS}
+icc -fno-strict-aliasing ${ICCARGS}
+ret=$?
+
+(( $ret == 0 )) && exit 0
+echo ">>>>>icc-wrapper ${ARGS} <<<<<>>>>>icc ${ICCARGS} <<<<< failed with status $ret. Launching gcc..."  >> /tmp/fuck-icc.log && gcc ${ARGS}
 exit $?
